/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.starrocks.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.20.0)", date = "2025-06-16")
public class TDataCacheOptions implements org.apache.thrift.TBase<TDataCacheOptions, TDataCacheOptions._Fields>, java.io.Serializable, Cloneable, Comparable<TDataCacheOptions> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TDataCacheOptions");

  private static final org.apache.thrift.protocol.TField ENABLE_POPULATE_DATACACHE_FIELD_DESC = new org.apache.thrift.protocol.TField("enable_populate_datacache", org.apache.thrift.protocol.TType.BOOL, (short)2);
  private static final org.apache.thrift.protocol.TField PRIORITY_FIELD_DESC = new org.apache.thrift.protocol.TField("priority", org.apache.thrift.protocol.TType.I32, (short)100);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TDataCacheOptionsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TDataCacheOptionsTupleSchemeFactory();

  public boolean enable_populate_datacache; // optional
  public int priority; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ENABLE_POPULATE_DATACACHE((short)2, "enable_populate_datacache"),
    PRIORITY((short)100, "priority");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 2: // ENABLE_POPULATE_DATACACHE
          return ENABLE_POPULATE_DATACACHE;
        case 100: // PRIORITY
          return PRIORITY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ENABLE_POPULATE_DATACACHE_ISSET_ID = 0;
  private static final int __PRIORITY_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.ENABLE_POPULATE_DATACACHE,_Fields.PRIORITY};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ENABLE_POPULATE_DATACACHE, new org.apache.thrift.meta_data.FieldMetaData("enable_populate_datacache", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.PRIORITY, new org.apache.thrift.meta_data.FieldMetaData("priority", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TDataCacheOptions.class, metaDataMap);
  }

  public TDataCacheOptions() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TDataCacheOptions(TDataCacheOptions other) {
    __isset_bitfield = other.__isset_bitfield;
    this.enable_populate_datacache = other.enable_populate_datacache;
    this.priority = other.priority;
  }

  @Override
  public TDataCacheOptions deepCopy() {
    return new TDataCacheOptions(this);
  }

  @Override
  public void clear() {
    setEnable_populate_datacacheIsSet(false);
    this.enable_populate_datacache = false;
    setPriorityIsSet(false);
    this.priority = 0;
  }

  public boolean isEnable_populate_datacache() {
    return this.enable_populate_datacache;
  }

  public TDataCacheOptions setEnable_populate_datacache(boolean enable_populate_datacache) {
    this.enable_populate_datacache = enable_populate_datacache;
    setEnable_populate_datacacheIsSet(true);
    return this;
  }

  public void unsetEnable_populate_datacache() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ENABLE_POPULATE_DATACACHE_ISSET_ID);
  }

  /** Returns true if field enable_populate_datacache is set (has been assigned a value) and false otherwise */
  public boolean isSetEnable_populate_datacache() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ENABLE_POPULATE_DATACACHE_ISSET_ID);
  }

  public void setEnable_populate_datacacheIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ENABLE_POPULATE_DATACACHE_ISSET_ID, value);
  }

  public int getPriority() {
    return this.priority;
  }

  public TDataCacheOptions setPriority(int priority) {
    this.priority = priority;
    setPriorityIsSet(true);
    return this;
  }

  public void unsetPriority() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PRIORITY_ISSET_ID);
  }

  /** Returns true if field priority is set (has been assigned a value) and false otherwise */
  public boolean isSetPriority() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PRIORITY_ISSET_ID);
  }

  public void setPriorityIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PRIORITY_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ENABLE_POPULATE_DATACACHE:
      if (value == null) {
        unsetEnable_populate_datacache();
      } else {
        setEnable_populate_datacache((java.lang.Boolean)value);
      }
      break;

    case PRIORITY:
      if (value == null) {
        unsetPriority();
      } else {
        setPriority((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ENABLE_POPULATE_DATACACHE:
      return isEnable_populate_datacache();

    case PRIORITY:
      return getPriority();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ENABLE_POPULATE_DATACACHE:
      return isSetEnable_populate_datacache();
    case PRIORITY:
      return isSetPriority();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TDataCacheOptions)
      return this.equals((TDataCacheOptions)that);
    return false;
  }

  public boolean equals(TDataCacheOptions that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_enable_populate_datacache = true && this.isSetEnable_populate_datacache();
    boolean that_present_enable_populate_datacache = true && that.isSetEnable_populate_datacache();
    if (this_present_enable_populate_datacache || that_present_enable_populate_datacache) {
      if (!(this_present_enable_populate_datacache && that_present_enable_populate_datacache))
        return false;
      if (this.enable_populate_datacache != that.enable_populate_datacache)
        return false;
    }

    boolean this_present_priority = true && this.isSetPriority();
    boolean that_present_priority = true && that.isSetPriority();
    if (this_present_priority || that_present_priority) {
      if (!(this_present_priority && that_present_priority))
        return false;
      if (this.priority != that.priority)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetEnable_populate_datacache()) ? 131071 : 524287);
    if (isSetEnable_populate_datacache())
      hashCode = hashCode * 8191 + ((enable_populate_datacache) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetPriority()) ? 131071 : 524287);
    if (isSetPriority())
      hashCode = hashCode * 8191 + priority;

    return hashCode;
  }

  @Override
  public int compareTo(TDataCacheOptions other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetEnable_populate_datacache(), other.isSetEnable_populate_datacache());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnable_populate_datacache()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.enable_populate_datacache, other.enable_populate_datacache);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPriority(), other.isSetPriority());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPriority()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.priority, other.priority);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TDataCacheOptions(");
    boolean first = true;

    if (isSetEnable_populate_datacache()) {
      sb.append("enable_populate_datacache:");
      sb.append(this.enable_populate_datacache);
      first = false;
    }
    if (isSetPriority()) {
      if (!first) sb.append(", ");
      sb.append("priority:");
      sb.append(this.priority);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TDataCacheOptionsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TDataCacheOptionsStandardScheme getScheme() {
      return new TDataCacheOptionsStandardScheme();
    }
  }

  private static class TDataCacheOptionsStandardScheme extends org.apache.thrift.scheme.StandardScheme<TDataCacheOptions> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, TDataCacheOptions struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 2: // ENABLE_POPULATE_DATACACHE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.enable_populate_datacache = iprot.readBool();
              struct.setEnable_populate_datacacheIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 100: // PRIORITY
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.priority = iprot.readI32();
              struct.setPriorityIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, TDataCacheOptions struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetEnable_populate_datacache()) {
        oprot.writeFieldBegin(ENABLE_POPULATE_DATACACHE_FIELD_DESC);
        oprot.writeBool(struct.enable_populate_datacache);
        oprot.writeFieldEnd();
      }
      if (struct.isSetPriority()) {
        oprot.writeFieldBegin(PRIORITY_FIELD_DESC);
        oprot.writeI32(struct.priority);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TDataCacheOptionsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TDataCacheOptionsTupleScheme getScheme() {
      return new TDataCacheOptionsTupleScheme();
    }
  }

  private static class TDataCacheOptionsTupleScheme extends org.apache.thrift.scheme.TupleScheme<TDataCacheOptions> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TDataCacheOptions struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetEnable_populate_datacache()) {
        optionals.set(0);
      }
      if (struct.isSetPriority()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetEnable_populate_datacache()) {
        oprot.writeBool(struct.enable_populate_datacache);
      }
      if (struct.isSetPriority()) {
        oprot.writeI32(struct.priority);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TDataCacheOptions struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.enable_populate_datacache = iprot.readBool();
        struct.setEnable_populate_datacacheIsSet(true);
      }
      if (incoming.get(1)) {
        struct.priority = iprot.readI32();
        struct.setPriorityIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

